"""SQLAlchemy 数据模型集合。"""

from .auth import (
    OperationLog,
    Permission,
    ROLE_GRADE_HEAD,
    ROLE_HEAD_TEACHER,
    ROLE_LABELS,
    ROLE_PSY_TEACHER,
    ROLE_SCHOOL_ADMIN,
    ROLE_SUBJECT_TEACHER,
    ROLE_SUPER_ADMIN,
    Role,
    RolePermission,
    User,
    UserRole,
)
from .base import BaseModel, SoftDeleteMixin, TimestampMixin
from .classroom import (
    AnalysisTask,
    AttendanceRecord,
    BehaviorRecord,
    ClassSession,
    EmotionRecord,
    Video,
)
from .face import FaceEmbedding
from .alert import Alert, Exam, InterventionRecord, Score
from .psychology import (
    AIConversation,
    AIConversationMessage,
    EmotionTimeline,
    Scale,
    ScaleAssessment,
    ScaleQuestion,
    TextAnalysis,
)
from .organization import (
    Clazz,
    Grade,
    GradeHead,
    School,
    Student,
    Subject,
    Teacher,
    TeacherClassSubject,
)

__all__ = [
    "BaseModel",
    "SoftDeleteMixin",
    "TimestampMixin",
    "School",
    "Grade",
    "Clazz",
    "Student",
    "Subject",
    "Teacher",
    "TeacherClassSubject",
    "GradeHead",
    "User",
    "Role",
    "Permission",
    "RolePermission",
    "UserRole",
    "OperationLog",
    "FaceEmbedding",
    "ClassSession",
    "Video",
    "AnalysisTask",
    "BehaviorRecord",
    "EmotionRecord",
    "AttendanceRecord",
    "Scale",
    "ScaleQuestion",
    "ScaleAssessment",
    "TextAnalysis",
    "AIConversation",
    "AIConversationMessage",
    "EmotionTimeline",
    "Exam",
    "Score",
    "Alert",
    "InterventionRecord",
    "ROLE_SUPER_ADMIN",
    "ROLE_SCHOOL_ADMIN",
    "ROLE_PSY_TEACHER",
    "ROLE_GRADE_HEAD",
    "ROLE_HEAD_TEACHER",
    "ROLE_SUBJECT_TEACHER",
    "ROLE_LABELS",
]
